sduo: required
services:
    - docker 

before_install:
    - docker build -t slemankhadoor/docker-react -f Dockerfile.dev .

script: 
    - docker run slemankhadoor/docker-react npm run test -- --coverage 